title: Knowledgebase
url: "https://gandhi-97.github.io/base-jekyll-template"
baseurl:
port: 4210
google_analytics_key:
disqus_shortname: jijitechnologiesblog.disqus.com
newsletter_action:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /assets/images/kb.png
description: A KnowledgeBase Project.
keywords: Test1,test2,test3
image:
  path: /assets/images/kb.png
  height: 100
  width: 100
author:
  name: JiJi Technologies
  email: contact@jijitechnologies.com
  twitter: jijitech # twitter username without the @ symbol
twitter:
  card: "summary"
  username: "jijitech"
facebook:
  app_id: 987654321
  publisher: 987654321   
  admins: 987654321
social:
  name: JiJi Technologies
  links:
    - https://twitter.com/jijitech
    - https://www.instagram/jijitech
    - https://www.facebook.com/jijitech

timezone: "America/Vancouver"
date_format: "%B %-d, %Y"
link-tags: true

permalink: /:categories/:title

plugins:
  - jekyll-extract-element
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  sets:


jekyll-archives:
  enabled: ['categories']
  layout: archive

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      image: "/assets/images/kb.png"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      comments: true
  -
    scope:
      type: "sets"
    values:
      _hide_content: true
  -
    scope:
      path: "index.html"
    values:
      body_class: "show_hero_search"

social_icons:
  - Facebook
  - LinkedIn
  - Twitter
  - YouTube
  - Email

types:
  - Document
  - Video

_comments:
